// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Architecture {
    using System;
    using UnityEngine;
    
    
    [System.SerializableAttribute()]
    public class BoolReference : Architecture.Reference<BoolVariable, bool> {
        
public static implicit operator bool(BoolReference reference)
                        {
                            if(reference.UseConstant)
                            {
                                return reference.ConstantValue;
                            }
                            return reference.Value;
                        }
                
    }
}
