// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Architecture {
    using System;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    [UnityEngine.CreateAssetMenuAttribute(menuName = "Game Events/EntityGameEvent")]
    public class EntityGameEvent : UnityEngine.ScriptableObject {
        
        [UnityEngine.SerializeField()]
        private Entity testVariable0;
        
        private System.Collections.Generic.List<EntityGameEventListener> _listeners = new List<EntityGameEventListener>();
        
        public void Invoke(Entity param0) {
            int i;
            for (i = _listeners.Count - 1; (i >= 0); i = (i - 1)) {
_listeners[i].Invoke(param0);
            }
        }
        
        public void InvokeWithTestingParams() {
            this.Invoke(testVariable0);
        }
        
        public void AddListener(EntityGameEventListener param0) {
            if(!_listeners.Contains(param0)) _listeners.Add(param0);
        }
        
        public void RemoveListener(EntityGameEventListener param0) {
            _listeners.Remove(param0);
        }
    }
}
