// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Architecture {
    using System;
    using UnityEngine;
    
    
    public class EntityGameEventListener : UnityEngine.MonoBehaviour {
        
        public EntityEvent Response;
        
        public EntityGameEvent GameEvent;
        
        private void OnEnable() {
            GameEvent.AddListener(this);
        }
        
        private void OnDisable() {
            GameEvent.RemoveListener(this);
        }
        
        public void Invoke(Entity param0) {
Response.Invoke(param0);
        }
    }
}
